### ISSUE TITLE
bundle-update command?

### ISSUE THREAD

**Issue by vbauerster** [jdugan6240/kak-bundle#15]
It looks like `bundle-install` command just replaces registered plugins rather than updating, correct me if I wrong. I found this because of my slow internet connection. After I run `bundle-install` and re-opened kakoune I found that some plugins were missing. It turns out that `git clone` command in my case sometimes succeeds and most of the time timeouts. So it would be nice to have real `bundle-update` command which would `git pull` each plugin.

**Comment by jdugan6240** [comment]
Yeah, that would be ideal. However, since `kak-bundle` allows for installation of plugins with any method, from git to symlinks to even mercurial if desired, there's no guarantee that `git pull` would be correct with the current design.

A possible solution that I came up with was for `git pull` to be the default whenever `bundle-update` is called, and this default could be changed with a `bundle-updater` command - similar to the existing `bundle-install-hook` and `bundle-cleaner` commands.

What do you think?

**Comment by vbauerster** [comment]
> A possible solution that I came up with was for `git pull` to be the default whenever `bundle-update` is called, and this default could be changed with a `bundle-updater` command - similar to the existing `bundle-install-hook` and `bundle-cleaner` commands.

That's really nice idea. `git pull` is sensible default for update command.

**Comment by vbauerster** [comment]
I just noticed that `bundle-install` has plugin name completion. This is great you did amazing job. This partially solves my problem with slow connection as I can re-install a single plugin, however some plugins may grow in size over time and re-installing even a single one can take considerable amount of time. Average users, me including, tend to update all with a single command and expect no breaking changes, so even if `git pull` will timeout it won't leave a plugin in incomplete state, contrary to `git clone` from scratch operation.

**Comment by jdugan6240** [comment]
Sorry for the long wait - I don't have nearly as much free time nowadays as I'd like.

The `bundle-update` and `bundle-updater` commands have been implemented. Let me know if it works for you, because it seems to work on my end.

**Comment by vbauerster** [comment]
Yes it works as expected. Thanks for your time and work.
